### ISSUE TITLE
Windows 10 error

### ISSUE THREAD

**Issue by tonysmartantzoulatos** [heldersepu/GMapCatcher#495]
Installed the software on windows 10 and seems to give me an error.

Traceback (most recent call last):
  File "maps.py", line 15, in <module>
  File "gmapcatcher\mapGPS.pyc", line 11, in <module>
  File "gmapcatcher\mapConst.pyc", line 160, in <module>
LookupError: unknown encoding: cp65001

**Comment by Gaylian** [comment]
Having same problem with Win 11.

**Comment by AdamZadorski97** [comment]
Any ideas how to solve it?
